# Generated by Django 4.1.6 on 2023-03-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('img', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('img', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('stars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('rol', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Stores',
        ),
    ]
